import { Express, Request, Response } from 'express';
import repository from '../database/repository';
import { ValidationError, NotFoundError, ForbiddenError } from '../utils/errors';
import { sendEmailViaGmail } from '../services/gmailService';

async function getBrandId(req: Request): Promise<string> {
  const brandId = req.query.brandId as string;
  if (!brandId) throw new ValidationError('brandId is required');
  const brand = await repository.findBrandById(brandId);
  if (!brand) throw new NotFoundError('Brand not found');
  const userId = (req as any).userId;
  if (!await repository.canAccessBrand(brand.id, userId)) throw new ForbiddenError();
  return brand.id;
}

const BUILT_IN_REPORT_TYPES = ['revenue', 'orders', 'inventory', 'customers', 'returns', 'sla', 'business', 'custom'];

function buildReportHTML(reportName: string, brandName: string, type: string, data: any, filters: any): string {
  const dateLabel = filters.start_date
    ? `${new Date(filters.start_date).toLocaleDateString('en-IN')} – ${filters.end_date ? new Date(filters.end_date).toLocaleDateString('en-IN') : 'now'}`
    : 'All time';

  const numericRows = Object.entries(data)
    .filter(([, v]) => typeof v === 'number')
    .map(([k, v]) => {
      const label = k.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ').trim();
      const isMonetary = /revenue|value|spent|amount/i.test(k);
      const formatted = isMonetary ? `₹${(v as number).toLocaleString('en-IN')}` : String(v);
      return `<tr><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;color:#6b7280;font-size:13px">${label}</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-weight:600;font-size:13px;text-align:right">${formatted}</td></tr>`;
    })
    .join('');

  return `<!DOCTYPE html><html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:24px">
<div style="max-width:600px;margin:0 auto;background:white;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden">
  <div style="background:#10b981;padding:24px">
    <h1 style="color:white;margin:0;font-size:20px">${reportName}</h1>
    <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:13px">${brandName} · ${dateLabel}</p>
  </div>
  <div style="padding:20px">
    <p style="font-size:12px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;font-weight:600;margin:0 0 12px">${type} Report</p>
    <table style="width:100%;border-collapse:collapse">${numericRows}</table>
  </div>
  <div style="padding:16px 20px;background:#f9fafb;border-top:1px solid #f3f4f6">
    <p style="margin:0;font-size:11px;color:#9ca3af">Generated by BRDG Alpha · ${new Date().toLocaleString('en-IN')}</p>
  </div>
</div></body></html>`;
}

export function setupReportsRoutes(app: Express) {
  // List reports
  app.get('/api/reports', async (req: Request, res: Response) => {
    try {
      const brandId = await getBrandId(req);
      const reports = await repository.findReportsByBrand(brandId);
      res.json({ reports });
    } catch (err: any) {
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // Create report
  app.post('/api/reports', async (req: Request, res: Response) => {
    try {
      const brandId = await getBrandId(req);
      const { name, type, config } = req.body;
      if (!name || !type) throw new ValidationError('name and type are required');
      // Allow any type (built-in or custom user-defined)
      const finalType = typeof type === 'string' && type.trim() ? type.trim() : 'custom';
      const report = await repository.createReport({ brandId, name, type: finalType, config: config || {} });
      res.status(201).json({ report });
    } catch (err: any) {
      res.status(err.status || 400).json({ message: err.message });
    }
  });

  // Run / generate report
  app.post('/api/reports/:id/run', async (req: Request, res: Response) => {
    try {
      const userId = (req as any).userId as string;
      const report = await repository.prisma.report.findUnique({ where: { id: req.params.id } });
      if (!report) throw new NotFoundError('Report not found');
      if (!await repository.canAccessBrand(report.brandId, userId)) throw new ForbiddenError();

      const brandId = report.brandId;
      const config: any = report.config || {};
      const filters = {
        start_date: config.start_date || req.body.start_date,
        end_date: config.end_date || req.body.end_date,
      };

      let data: any = {};
      switch (report.type) {
        case 'revenue':
        case 'orders': {
          const orders = await repository.findOrdersByBrand(brandId, filters);
          const delivered = orders.filter(o => o.status === 'delivered');
          const pending   = orders.filter(o => o.status === 'pending');
          data = {
            totalOrders: orders.length,
            totalRevenue: orders.reduce((s, o) => s + o.amount, 0),
            deliveredOrders: delivered.length,
            pendingOrders: pending.length,
            byStatus: orders.reduce((acc: any, o) => { acc[o.status] = (acc[o.status] || 0) + 1; return acc; }, {}),
          };
          break;
        }
        case 'inventory': {
          const items = await repository.findInventoryByBrand(brandId);
          data = {
            totalSkus: items.length,
            totalValue: items.reduce((s, i) => s + i.salePrice * i.stockLevel, 0),
            lowStock: items.filter(i => i.stockLevel <= i.reorderPoint).length,
            outOfStock: items.filter(i => i.stockLevel === 0).length,
          };
          break;
        }
        case 'customers': {
          const customers = await repository.findCustomersByBrand(brandId, filters);
          data = {
            totalCustomers: customers.length,
            totalSpent: customers.reduce((s, c) => s + c.totalSpent, 0),
            repeatCustomers: customers.filter(c => c.totalOrders > 1).length,
          };
          break;
        }
        case 'returns': {
          const returns = await repository.findReturnsByBrand(brandId, filters);
          data = {
            totalReturns: returns.length,
            totalValue: returns.reduce((s, r) => s + r.amount, 0),
            byReason: returns.reduce((acc: any, r) => { acc[r.reason || 'Other'] = (acc[r.reason || 'Other'] || 0) + 1; return acc; }, {}),
          };
          break;
        }
        case 'business': {
          const [orders, customers, inventory, returns] = await Promise.all([
            repository.findOrdersByBrand(brandId, filters),
            repository.findCustomersByBrand(brandId, {}),
            repository.findInventoryByBrand(brandId, { trackedOnDashboard: true }),
            repository.findReturnsByBrand(brandId, filters),
          ]);
          const delivered = orders.filter(o => o.status === 'delivered');
          const totalRevenue = orders.reduce((s, o) => s + o.amount, 0);
          const returnValue  = returns.reduce((s, r) => s + (r.amount ?? 0), 0);
          data = {
            totalRevenue,
            netRevenue: Math.max(0, totalRevenue - returnValue),
            totalOrders: orders.length,
            deliveredOrders: delivered.length,
            pendingOrders: orders.filter(o => o.status === 'pending').length,
            cancelledOrders: orders.filter(o => o.status === 'cancelled').length,
            avgOrderValue: orders.length ? Math.round(totalRevenue / orders.length) : 0,
            totalCustomers: customers.length,
            repeatCustomers: customers.filter(c => c.totalOrders > 1).length,
            totalReturns: returns.length,
            returnValue,
            lowStockSkus: inventory.filter(i => i.stockLevel > 0 && i.stockLevel <= i.reorderPoint).length,
            outOfStockSkus: inventory.filter(i => i.stockLevel === 0).length,
          };
          break;
        }
        default:
          data = {};
      }

      await repository.updateReport(req.params.id, { lastGenerated: new Date() });
      res.json({ report: { ...report, lastGenerated: new Date() }, data });
    } catch (err: any) {
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // Email a report
  app.post('/api/reports/:id/email', async (req: Request, res: Response) => {
    try {
      const userId = (req as any).userId as string;
      const report = await repository.prisma.report.findUnique({ where: { id: req.params.id } });
      if (!report) throw new NotFoundError('Report not found');
      if (!await repository.canAccessBrand(report.brandId, userId)) throw new ForbiddenError();

      const { recipients, start_date, end_date } = req.body as {
        recipients: string[];
        start_date?: string;
        end_date?: string;
      };
      if (!recipients || recipients.length === 0) throw new ValidationError('recipients is required');

      const brand = await repository.findBrandById(report.brandId);
      const config: any = report.config || {};
      const filters = {
        start_date: start_date || config.start_date,
        end_date:   end_date   || config.end_date,
      };

      // Build report data (reuse logic)
      let data: any = {};
      switch (report.type) {
        case 'revenue': case 'orders': {
          const orders = await repository.findOrdersByBrand(report.brandId, filters);
          data = {
            totalOrders: orders.length,
            totalRevenue: orders.reduce((s, o) => s + o.amount, 0),
            deliveredOrders: orders.filter(o => o.status === 'delivered').length,
            pendingOrders: orders.filter(o => o.status === 'pending').length,
          };
          break;
        }
        case 'customers': {
          const customers = await repository.findCustomersByBrand(report.brandId, {});
          data = {
            totalCustomers: customers.length,
            totalSpent: customers.reduce((s, c) => s + c.totalSpent, 0),
            repeatCustomers: customers.filter(c => c.totalOrders > 1).length,
          };
          break;
        }
        case 'inventory': {
          const items = await repository.findInventoryByBrand(report.brandId);
          data = {
            totalSkus: items.length,
            lowStockSkus: items.filter(i => i.stockLevel <= i.reorderPoint).length,
            outOfStockSkus: items.filter(i => i.stockLevel === 0).length,
          };
          break;
        }
        case 'returns': {
          const returns = await repository.findReturnsByBrand(report.brandId, filters);
          data = {
            totalReturns: returns.length,
            totalValue: returns.reduce((s, r) => s + r.amount, 0),
          };
          break;
        }
        case 'business': {
          const [orders, customers, inventory, returns] = await Promise.all([
            repository.findOrdersByBrand(report.brandId, filters),
            repository.findCustomersByBrand(report.brandId, {}),
            repository.findInventoryByBrand(report.brandId, { trackedOnDashboard: true }),
            repository.findReturnsByBrand(report.brandId, filters),
          ]);
          const totalRevenue = orders.reduce((s, o) => s + o.amount, 0);
          const returnValue  = returns.reduce((s, r) => s + (r.amount ?? 0), 0);
          data = {
            totalRevenue,
            netRevenue: Math.max(0, totalRevenue - returnValue),
            totalOrders: orders.length,
            deliveredOrders: orders.filter(o => o.status === 'delivered').length,
            pendingOrders: orders.filter(o => o.status === 'pending').length,
            totalCustomers: customers.length,
            totalReturns: returns.length,
            lowStockSkus: inventory.filter(i => i.stockLevel <= i.reorderPoint).length,
          };
          break;
        }
        default: data = {};
      }

      const html = buildReportHTML(report.name, brand?.name ?? 'Brand', report.type, data, filters);
      const subject = `Report: ${report.name} — ${brand?.name ?? ''}`;

      // Send to each recipient (uses the boss's Gmail OAuth)
      const failures: string[] = [];
      for (const email of recipients) {
        try {
          await sendEmailViaGmail(userId, email.trim(), subject, html);
        } catch {
          failures.push(email.trim());
        }
      }

      await repository.updateReport(req.params.id, { lastGenerated: new Date() });

      if (failures.length === recipients.length) {
        return res.status(502).json({ message: 'Failed to send to all recipients. Check Gmail connection in Settings.' });
      }
      res.json({
        message: failures.length
          ? `Sent to ${recipients.length - failures.length} recipient(s). Failed: ${failures.join(', ')}`
          : `Report emailed to ${recipients.length} recipient(s)`,
        failures,
      });
    } catch (err: any) {
      res.status(err.status || 500).json({ message: err.message });
    }
  });

  // Delete report
  app.delete('/api/reports/:id', async (req: Request, res: Response) => {
    try {
      const userId = (req as any).userId as string;
      const report = await repository.prisma.report.findUnique({ where: { id: req.params.id } });
      if (!report) throw new NotFoundError('Report not found');
      if (!await repository.canAccessBrand(report.brandId, userId)) throw new ForbiddenError();
      await repository.deleteReport(req.params.id);
      res.json({ message: 'Report deleted' });
    } catch (err: any) {
      res.status(err.status || 500).json({ message: err.message });
    }
  });
}
